```{r
 library(mgcv)
 set.seed(0)
 dat <- gamSim(5,n=200,scale=2)
 b<-gam(y ~ x0 + s(x1) + s(x2) + s(x3),data=dat)
 anova(b)
 b1<-gam(y ~ x0 + s(x1) + s(x2),data=dat)
 anova(b,b1,test="F")
```

```{r}
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")

devtools::install_github("mfasiolo/electBook")

```

```{r}
library(electBook)
 library(dplyr)
 library(tibble)
 data(IrishAgg)
 head(as_tibble(IrishAgg))
```

```{r}
library(mgcv)
 fitIRI<-gam(dem~dem48+dow+s(temp)+s(temp95)+
 s(tod,bs="cc")+s(toy,bs="cc"),
 knots=list(tod=c(0,48),
 toy=c(0,1)),
 data=IrishAgg)
```

```{r}
#install.packages("mgcViz")
library(mgcViz)
 fitIRI <- getViz(fitIRI, nsim = 50)
 class(fitIRI)
```

```{r}
 check1D(fitIRI, "dem48") + l_gridCheck1D(level = 0.95, showReps = FALSE)
```

```{r}
 check1D(fitIRI, "toy") + l_gridCheck1D(level = 0.95, showReps = FALSE)
```

```{r}
qq<-qq(fitIRI,method="tnormal",CI="normal",level=0.95)
```

```{r}
 check(fitIRI)

```

```{r}
 fitIRI_2<-gamV(dem~dow+s(dem48,k=10)+
 s(temp,k=20)+s(temp95,k=20)+
 s(tod,k=20,bs="cc")+s(toy,k=20),
 data=IrishAgg,
 family= scat,
 aGam=list(knots= list(tod= c(0,48))),
 aViz=list(nsim=50))
```
 
```{r}
 AIC(fitIRI,fitIRI_2)
 check(fitIRI_2)
```

```{r}
 print(plot(fitIRI_2,allTerms=TRUE),pages=1,
 layout_matrix=matrix(1:6,3,2))
```
